### ISSUE TITLE
Unable to edit table content

### ISSUE THREAD

**Issue by BaskarMN** [Anubhavjain786/grapesjs-table#3]
Thanks for your work. I was looking for a way to create table component in GrapesJS for days. Found your plug-in. I'm using this in a React application. I'm able to insert the table into the canvas, but I'm unable to edit the content. Only a blank table is appearing with the specified number of rows and columns. Please provide a solution. Am I missing something here? 

[tablejs.txt](https://github.com/Anubhavjain786/grapesjs-table/files/5607991/tablejs.txt)

**Comment by Anubhavjain786** [comment]
You can drag any other components into table cell
